---
- name: Test
  become: false
  hosts: crunchify-group
  tasks:
     
     - name: See history
       shell: cat ~/.bash_history
       register: command_output

     - debug:
                var: command_output.stdout_lines
                
     - local_action: copy content={{ command_output.stdout_lines }} dest=/home/kimngan/Analysis_Students_Manipulation/output/{{ inventory_hostname }}.txt

 
