---
- name: Test
  become: false
  hosts: crunchify-group
  tasks:
  
     #- name: Remove history command
     #  shell: rm /home/minhtrung0205/.bash_history
  
     #- name: See history
     #  shell: echo "export HISTTIMEFORMAT=\"%d/%m/%y %T \"" >> /home/minhtrung0205/.bashrc
     #  register: command_output
     
     #- name: Save bashrc
     #  shell: source /home/minhtrung0205/.bashrc
     #  args:
     #           executable: /bin/bash
     
     - name: See history
       shell: cat ~/.bash_history
       register: command_output

     - debug:
                var: command_output.stdout_lines
                
     - local_action: copy content={{ command_output.stdout_lines }} dest=/home/kimngan/Analysis_Students_Manipulation/output/{{ inventory_hostname }}.txt

 
